#!/usr/bin/env python3
import argparse
import matplotlib.pyplot as plt
import meterplot

plt.style.use('ggplot')


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Show energy consumption data'
        )
    parser.add_argument(
            'infile',
            type=str,
            help='input data YAML file'
            )
    return parser.parse_args()


if __name__ == '__main__':
    args = _parse_cmd_arguments()
    infile = args.infile

    unit, groups = meterplot.read_data(infile)
    # add average per second between the datetimes
    for group in groups:
        for meter in group['meters']:
            meter['aps'] = meterplot.average_per_second(
                meter['datetimes'],
                meter['values']
                )

    # merge across meters
    data = []
    for group in groups:
        datetimes_combined, averages_combined = \
            meterplot.merge_meters(group['meters'])
        data.append({
            'datetimes': datetimes_combined,
            'aps': averages_combined,
            'style': group['style'],
            })

    meterplot.show(unit, data)

    plt.show()
